version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ./bot_persistence:/app/bot_persistence

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: household
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d household"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
