"""Business rules constants."""

CLAIM_DEFER_MINUTES = 30
FIRST_DEFER_PENALTY = 0.2
SECOND_DEFER_PENALTY = 0.4
CLAIM_REMINDER_MINUTES = 120
CANCEL_GRACE_MINUTES = 5
CANCEL_LATE_PENALTY = 10
MISS_PENALTY_MULTIPLIER = 2
VOTE_SECOND_WAIT_MINUTES = 15
